server:
    port: 8080
spring:
    application:
        name: customer

    r2dbc:
        url: r2dbc:postgresql://amigoscode:password@localhost:5432/customer
        pool:
            enabled: true
            initial-size: 5
            max-size: 10

    logging:
        level:
            org.springframework.r2dbc: DEBUG

    zipkin:
        base-url: http://localhost:9411
    rabbitmq:
        addresses: localhost:5672
    profiles:
        active: default
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true

